name: leetomatic

on:
  schedule:
    - cron: '30 6 * * *'  # Runs at 6:30 AM UTC every day (12:00 PM IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  solve-leetcode-problem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run the script
        run: node leetomatic.js
        env:
          LEETCODE_SESSION_COOKIE: ${{ secrets.LEETCODE_SESSION_COOKIE }}
          GT_TOKEN: ${{ secrets.GT_TOKEN }}